### ISSUE TITLE
Fireball Rev.

### ISSUE THREAD

**Issue by davidbitton** [ugcs/ddc#2]
The documentation shows a Fireball board at Rev. E. but the repo has Rev D. Thanks.

**Comment by syakupov** [comment]
We had experimented with different type of LED drivers and issued revision E of the board. But the LED driver used in revision D proved to be optimal, therefore this revision was declared final.
Sorry for confusing, we are to update Figure 86 in the Hardware Manual.

**Comment by davidbitton** [comment]
Must the board be aluminum? Also, as you know, the LED modules are not available through retailers outside of China. Any reason why I can't revise it to be discrete red, green, and blue LEDs?

**Comment by davidbitton** [comment]
BTW, I was wondering if I can just make the bottom plate of an F450 the fireball PCB? The original F450s from DJI are PCBs, so no reason why I can't fab the fireball as an F450 bottom plate.
